### Linker spec file for Pokemon Diamond/Pearl US ###
###   Pass this to the SDK's makelcf.exe utility  ###
###        along with the ARM9-TS template.       ###

Static arm9
{
	Address 0x02004000
	Object main.o
	Object syscall.o
	Object main2.o
}

Autoload ITCM
{
	Address 0x02300000
	Object itcm.o
}

Autoload DTCM
{
	Address 0x0237D000
	Object dtcm.o
}

Autoload EXT
{
	Address 0x01FF8000
	Object ext.o
}
